#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Alistair Stead"
email = "62936+alistairstead@users.noreply.github.com"

[signing]
behavior = "own"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICqsrSxLYhMuCdzuO6pra5QulC8SKN19v1AUjh7wqUZq"

[signing.backends.ssh]
program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

[git]
auto-local-bookmark = true
sign-on-push = true

[fix.tools.biome]
command = ["bunx", "@biomejs/biome", "check", "--stdin-file-path=$path", "--write"]

patterns = [
    "glob:'**/*.js'",
    "glob:'**/*.jsx'",
    "glob:'**/*.ts'",
    "glob:'**/*.tsx'",
    "glob:'**/*.json'",
    ]

[ui]
diff-formatter = "ksdiff"
merge-editor = "ksdiff"

[merge-tools.ksdiff]
diff-invocation-mode = "file-by-file"
diff-args = ["--partial-changeset", "$left", "$right"]
merge-args = ["--merge", "--output", "$output", "--base", "$base", "$left", "$right"]
